version: '3'

services:
  frontend:
    build: ./Front_end_react  # 更改为 React 项目的相对路径
    volumes:
      - ./Front_end_react:/frontend  # 更改为 React 项目的相对路径
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://20.42.85.64
